skip_branch_with_pr: true
skip_tags: true

image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 0

install:
  - ps: |
      New-Item -Name bin -Force -ItemType Directory | Out-Null
      New-Item -Name obj -Force -ItemType Directory | Out-Null

      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile './obj/dotnet-install.ps1'
      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.sh' -OutFile './obj/dotnet-install.sh'

      if ('Win32NT' -eq [System.Environment]::OSVersion.Platform) {
        ./obj/dotnet-install.ps1 -InstallDir ./bin -JsonFile ./global.json -NoPath
      }

  - sh: |
      chmod +x ./obj/dotnet-install.sh
      ./obj/dotnet-install.sh -InstallDir ./bin -JsonFile ./global.json -NoPath

  - ps: |
      ./bin/dotnet --info
      ./bin/dotnet new tool-manifest
      ./bin/dotnet tool install codecov.tool

build_script:
  - ps: |
      [xml] $buildInfo = Get-Content ./BuildInfo.props

      $versionPrefix = $buildInfo.Project.PropertyGroup.VersionPrefix[0]
      $versionSuffix = "preview.$env:APPVEYOR_BUILD_NUMBER"

      if ('release' -eq $env:APPVEYOR_REPO_BRANCH) {
        Update-AppveyorBuild -Version $versionPrefix
        ./bin/dotnet build --configuration Release
        ./bin/dotnet pack --configuration Release --no-build
      } else {
        Update-AppveyorBuild -Version "$versionPrefix-$versionSuffix"
        ./bin/dotnet build --configuration Release --version-suffix $versionSuffix
        ./bin/dotnet pack --configuration Release --no-build --version-suffix $versionSuffix
      }

test_script:
  - ps: |
      ./bin/dotnet test --configuration Release --no-build --results-directory ./test-results --settings ./CodeCoverage.runsettings
      ./bin/dotnet codecov --file ./test-results/*/coverage.*.xml

artifacts:
  - path: src/**/*.nupkg
  - path: src/**/*.snupkg
