skip_tags: true

image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 0

install:
  - ps: New-Item -Name bin -Force -ItemType Directory | Out-Null
  - ps: New-Item -Name obj -Force -ItemType Directory | Out-Null
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile './obj/dotnet-install.ps1'
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.sh' -OutFile './obj/dotnet-install.sh'
  - cmd: PowerShell -Command ./obj/dotnet-install.ps1 -InstallDir ./bin -JsonFile ./global.json -NoPath
  - sh: chmod +x ./obj/dotnet-install.sh
  - sh: ./obj/dotnet-install.sh -InstallDir ./bin -JsonFile ./global.json -NoPath

build_script:
  - ps: ./bin/dotnet --info
  - ps: ./bin/dotnet new tool-manifest
  - ps: ./bin/dotnet tool install codecov.tool
  - ps: ./bin/dotnet build --configuration Release
  - ps: ./bin/dotnet pack --configuration Release --no-build

test_script:
  - ps: ./bin/dotnet test --configuration Release --no-build --results-directory ./test-results --settings ./Test.runsettings
  - ps: ./bin/dotnet codecov --file ./test-results/*/coverage.*.xml

artifacts:
  - path: src/**/*.nupkg
  - path: src/**/*.snupkg
