version: 1.2.1-ci.{build}

image:
  - Ubuntu
  - Visual Studio 2017

before_build:
  - ps: dotnet --info

build_script:
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -eq "release") { dotnet pack --configuration Release --include-symbols }'
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -ne "release") { dotnet pack --configuration Release --version-suffix "ci.$env:APPVEYOR_BUILD_NUMBER" --include-symbols }'

test_script:
  - ps: 'if ($env:OS -eq "Windows_NT") { dotnet test test/NeinMath.Tests/NeinMath.Tests.csproj --configuration Release --framework net461 }'
  - ps: 'dotnet test test/NeinMath.Tests/NeinMath.Tests.csproj --configuration Release --framework netcoreapp2.1 /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$PWD/TestResults/coverage.xml"'

after_test:
  - cmd: '"%UserProfile%\.nuget\packages\ReportGenerator\3.1.2\tools\ReportGenerator.exe" -reports:TestResults\coverage.xml -targetdir:TestResults\report -reporttypes:Badges;Html'

artifacts:
  - path: src/**/*.nupkg
  - path: TestResults

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
      ci_windows: true
  - provider: Environment
    name: nuget.org
    on:
      branch: release
      ci_windows: true
