version: 1.3.2-preview.{build}

image:
  - Ubuntu
  - Visual Studio 2019

before_build:
  - ps: dotnet --info

build_script:
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -eq "release") { dotnet pack --configuration Release --include-symbols }'
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -ne "release") { dotnet pack --configuration Release --version-suffix "preview.$env:APPVEYOR_BUILD_NUMBER" --include-symbols }'

test_script:
  - ps: 'dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="$PWD/coverage.xml" /p:Include="[NeinMath]*"'

after_test:
  - ps: dotnet tool install --global codecov.tool
  - ps: 'codecov --file coverage.*.xml --verbose'

artifacts:
  - path: src/**/*.nupkg
  - path: src/**/*.snupkg

deploy:
  - provider: Environment
    name: nuget.org
    on:
      branch: release
      ci_windows: true
