version: 1.3.2-ci.{build}

image:
  - Ubuntu
  - Visual Studio 2017

before_build:
  - ps: dotnet --info

build_script:
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -eq "release") { dotnet pack --configuration Release --include-symbols }'
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -ne "release") { dotnet pack --configuration Release --version-suffix "ci.$env:APPVEYOR_BUILD_NUMBER" --include-symbols }'

test_script:
  - ps: 'dotnet test test/NeinMath.Tests/NeinMath.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="$PWD/coverage.xml" /p:Include="[NeinMath]*"'

after_test:
  - cmd: 'curl -s https://codecov.io/bash | bash -s - -f coverage.xml'

artifacts:
  - path: src/**/*.nupkg
  - path: src/**/*.snupkg

deploy:
  - provider: Environment
    name: nuget.org
    on:
      branch: release
      ci_windows: true
