version: 1.2.0-ci.{build}

image:
- Visual Studio 2017
- Ubuntu

before_build:
  - ps: dotnet --info

build_script:
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -eq "release") { dotnet pack --configuration Release --include-symbols }'
  - ps: 'if ($env:APPVEYOR_REPO_BRANCH -ne "release") { dotnet pack --configuration Release --version-suffix "ci.$env:APPVEYOR_BUILD_NUMBER" --include-symbols }'

before_test:
  - cmd: dotnet msbuild test/NeinMath.Tests/NeinMath.Tests.csproj /t:Clean;Build /p:Configuration=Release;DebugType=Full

test_script:
  - cmd: dotnet msbuild test/NeinMath.Tests/NeinMath.Tests.csproj /t:OpenCover /p:Configuration=Release;TargetFramework=net461
  - cmd: dotnet msbuild test/NeinMath.Tests/NeinMath.Tests.csproj /t:OpenCover /p:Configuration=Release;TargetFramework=netcoreapp2.1
  - sh: dotnet test test/NeinMath.Tests/NeinMath.Tests.csproj --configuration Release --framework netcoreapp2.1

after_test:
  - cmd: dotnet msbuild test/NeinMath.Tests/NeinMath.Tests.csproj /t:ReportGenerator

artifacts:
  - path: src/**/*.nupkg
  - path: TestResults

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
      image: Visual Studio 2017
  - provider: Environment
    name: nuget.org
    on:
      branch: release
      image: Visual Studio 2017
