version: 1.0.2-ci{build}

skip_tags: true

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -Version 1.0.1 -NoPath'
  - ps: $env:PATH = "$env:DOTNET_INSTALL_DIR;$env:PATH"
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

build_script:
  - cmd: build

test_script:
  - cmd: test

artifacts:
  - path: 'src\**\*.nupkg'
  - path: TestResults

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
  - provider: Environment
    name: nuget.org
    on:
      branch: release
