version: 1.0.2-ci{build}

image: Visual Studio 2017

build_script:
  - cmd: set build_options=/p:VersionSuffix=ci%appveyor_build_number%
  - cmd: if [%appveyor_repo_branch%]==[release] set build_options=/p:VersionSuffix=
  - cmd: dotnet --info
  - cmd: dotnet restore %build_options%
  - cmd: dotnet build --configuration Debug %build_options%
  - cmd: dotnet build --configuration Release %build_options%
  - cmd: dotnet pack --configuration Release --include-symbols %build_options%

test_script:
  - cmd: if not exist TestResults mkdir TestResults
  - cmd: set opencover=%UserProfile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe
  - cmd: set reportgenerator=%UserProfile%\.nuget\packages\ReportGenerator\2.5.2\tools\ReportGenerator.exe
  - cmd: '"%opencover%" -target:dotnet.exe -targetargs:"test test\NeinMath.Tests\NeinMath.Tests.csproj --configuration Release --framework net461" -searchdirs:test\NeinMath.Tests\bin\Release\net461 -output:TestResults\NeinMath.netframework.report.xml -register:user -filter:+[NeinMath]* -returntargetcode -oldstyle'
  - cmd: '"%opencover%" -target:dotnet.exe -targetargs:"test test\NeinMath.Tests\NeinMath.Tests.csproj --configuration Release --framework netcoreapp1.1" -searchdirs:test\NeinMath.Tests\bin\Release\netcoreapp1.1 -output:TestResults\NeinMath.netcoreapp.report.xml -register:user -filter:+[NeinMath]* -returntargetcode -oldstyle'
  - cmd: '"%reportgenerator%" -reports:TestResults\*.report.xml -targetdir:TestResults\report -reporttypes:Badges;Html'

artifacts:
  - path: 'src\**\*.nupkg'
  - path: TestResults

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
  - provider: Environment
    name: nuget.org
    on:
      branch: release
