version: 1.0.2-ci{build}

skip_tags: true

build_script:
  - cmd: build

test_script:
  - cmd: test

artifacts:
  - path: '**\*.nupkg'
  - path: TestResults

cache:
  - '%UserProfile%\.nuget'

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
  - provider: Environment
    name: nuget.org
    on:
      branch: release
