version: 1.1.1-ci.{build}

image: Visual Studio 2017

before_build:
  - cmd: set build_options=--configuration Release --version-suffix ci.%appveyor_build_number%
  - cmd: if [%appveyor_repo_branch%]==[release] set build_options=--configuration Release

build_script:
  - cmd: dotnet --info
  - cmd: dotnet build %build_options%
  - cmd: dotnet pack %build_options% --include-symbols

before_test:
  - cmd: if not exist TestResults mkdir TestResults
  - cmd: set OpenCover=%UserProfile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe
  - cmd: set ReportGenerator=%UserProfile%\.nuget\packages\ReportGenerator\2.5.10\tools\ReportGenerator.exe

test_script:
  - cmd: dotnet clean --configuration Release
  - cmd: dotnet build %build_options% /p:DebugType=Full
  - cmd: cd test\NeinMath.Tests
  - cmd: '"%OpenCover%" -target:dotnet.exe -targetargs:"xunit -configuration Release -framework net452 -nobuild -xml ..\..\TestResults\NeinMath.netframework45.xml" -searchdirs:bin\Release\net452 -output:..\..\TestResults\NeinMath.netframework45.report.xml -register:user -filter:+[NeinMath]* -returntargetcode -oldstyle'
  - cmd: '"%OpenCover%" -target:dotnet.exe -targetargs:"xunit -configuration Release -framework netcoreapp1.1 -nobuild -xml ..\..\TestResults\NeinMath.netcore1.xml" -searchdirs:bin\Release\netcoreapp1.1 -output:..\..\TestResults\NeinMath.netcore1.report.xml -register:user -filter:+[NeinMath]* -returntargetcode -oldstyle'
  - cmd: '"%OpenCover%" -target:dotnet.exe -targetargs:"xunit -configuration Release -framework netcoreapp2.0 -nobuild -xml ..\..\TestResults\NeinMath.netcore2.xml" -searchdirs:bin\Release\netcoreapp2.0 -output:..\..\TestResults\NeinMath.netcore2.report.xml -register:user -filter:+[NeinMath]* -returntargetcode -oldstyle'
  - cmd: cd ..\..
  - cmd: '"%ReportGenerator%" -reports:TestResults\*.report.xml -targetdir:TestResults\report -reporttypes:Badges;Html'

artifacts:
  - path: 'src\**\*.nupkg'
  - path: TestResults

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
  - provider: Environment
    name: nuget.org
    on:
      branch: release
