name: everything
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        framework: [ 'net6.0' ]
        include:
        - os: windows-latest
          framework: net48
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
    - name: Run tests (${{ matrix.framework }})
      run: dotnet test --configuration Release --framework ${{ matrix.framework }} --results-directory test-results --settings test.runsettings
    - name: Publish coverage
      uses: codecov/codecov-action@v3
      with:
        file: test-results/*/coverage.opencover.xml
  package:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
    - name: Create packages (w/o version suffix)
      run: dotnet pack --configuration Release --include-symbols --output pkg
      if: startsWith(github.ref, 'refs/tags/v') == true
    - name: Create packages (w/ version suffix)
      run: dotnet pack --configuration Release --include-symbols --output pkg --version-suffix preview.${{ github.run_number }}
      if: startsWith(github.ref, 'refs/tags/v') != true
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: pkg
    if: github.event_name == 'push'
  prerelease:
    needs: package
    runs-on: windows-latest
    steps:
    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        name: packages
    - name: Publish packages
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    if: github.ref == 'refs/heads/main'
  release:
    needs: package
    runs-on: windows-latest
    steps:
    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        name: packages
    - name: Publish packages
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --source nuget.org
    if: startsWith(github.ref, 'refs/tags/v') == true
